/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LojistaRouteImport } from './routes/lojista'
import { Route as FuncionarioRouteImport } from './routes/funcionario'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojistaIndexRouteImport } from './routes/lojista.index'
import { Route as FuncionarioIndexRouteImport } from './routes/funcionario.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ValeCodigoRouteImport } from './routes/vale.$codigo'
import { Route as NpsIdRouteImport } from './routes/nps.$id'
import { Route as NotaSlugRouteImport } from './routes/nota.$slug'
import { Route as LojistaWidgetRouteImport } from './routes/lojista.widget'
import { Route as LojistaValePresenteRouteImport } from './routes/lojista.vale-presente'
import { Route as LojistaSorteiosRouteImport } from './routes/lojista.sorteios'
import { Route as LojistaResgatesRouteImport } from './routes/lojista.resgates'
import { Route as LojistaPromocoesRouteImport } from './routes/lojista.promocoes'
import { Route as LojistaProdutosRouteImport } from './routes/lojista.produtos'
import { Route as LojistaPersonalizacaoRouteImport } from './routes/lojista.personalizacao'
import { Route as LojistaOnboardingRouteImport } from './routes/lojista.onboarding'
import { Route as LojistaNpsRouteImport } from './routes/lojista.nps'
import { Route as LojistaNotasRouteImport } from './routes/lojista.notas'
import { Route as LojistaLoginRouteImport } from './routes/lojista.login'
import { Route as LojistaLancarVendaRouteImport } from './routes/lojista.lancar-venda'
import { Route as LojistaInstagramRouteImport } from './routes/lojista.instagram'
import { Route as LojistaEquipeRouteImport } from './routes/lojista.equipe'
import { Route as LojistaConfiguracoesRouteImport } from './routes/lojista.configuracoes'
import { Route as LojistaClientesRouteImport } from './routes/lojista.clientes'
import { Route as LojistaCampanhasRouteImport } from './routes/lojista.campanhas'
import { Route as LojistaAguardandoRouteImport } from './routes/lojista.aguardando'
import { Route as FuncionarioVouchersRouteImport } from './routes/funcionario.vouchers'
import { Route as FuncionarioResgatesRouteImport } from './routes/funcionario.resgates'
import { Route as FuncionarioPontuarRouteImport } from './routes/funcionario.pontuar'
import { Route as FuncionarioPerfilRouteImport } from './routes/funcionario.perfil'
import { Route as FuncionarioHistoricoRouteImport } from './routes/funcionario.historico'
import { Route as FuncionarioClientesRouteImport } from './routes/funcionario.clientes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicWidgetSlugRouteImport } from './routes/api/public/widget.$slug'
import { Route as ApiPublicWebhookOrigemRouteImport } from './routes/api/public/webhook/$origem'
import { Route as ApiPublicNpsSubmitRouteImport } from './routes/api/public/nps.submit'
import { Route as ApiPublicHooksNotificationsDailyRouteImport } from './routes/api/public/hooks/notifications-daily'
import { Route as ApiPublicHooksExpirarVouchersRouteImport } from './routes/api/public/hooks/expirar-vouchers'
import { Route as ApiPublicHooksExpirarPontosRouteImport } from './routes/api/public/hooks/expirar-pontos'
import { Route as ApiPublicHooksCampanhasAgendadasRouteImport } from './routes/api/public/hooks/campanhas-agendadas'
import { Route as ApiPublicWebhookOlistErpSlugRouteImport } from './routes/api/public/webhook/olist-erp.$slug'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaRoute = LojistaRouteImport.update({
  id: '/lojista',
  path: '/lojista',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioRoute = FuncionarioRouteImport.update({
  id: '/funcionario',
  path: '/funcionario',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaIndexRoute = LojistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojistaRoute,
} as any)
const FuncionarioIndexRoute = FuncionarioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FuncionarioRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ValeCodigoRoute = ValeCodigoRouteImport.update({
  id: '/vale/$codigo',
  path: '/vale/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsIdRoute = NpsIdRouteImport.update({
  id: '/nps/$id',
  path: '/nps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotaSlugRoute = NotaSlugRouteImport.update({
  id: '/nota/$slug',
  path: '/nota/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaWidgetRoute = LojistaWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaValePresenteRoute = LojistaValePresenteRouteImport.update({
  id: '/vale-presente',
  path: '/vale-presente',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaSorteiosRoute = LojistaSorteiosRouteImport.update({
  id: '/sorteios',
  path: '/sorteios',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaResgatesRoute = LojistaResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaPromocoesRoute = LojistaPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaProdutosRoute = LojistaProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaPersonalizacaoRoute = LojistaPersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaOnboardingRoute = LojistaOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaNpsRoute = LojistaNpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaNotasRoute = LojistaNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaLoginRoute = LojistaLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaLancarVendaRoute = LojistaLancarVendaRouteImport.update({
  id: '/lancar-venda',
  path: '/lancar-venda',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaInstagramRoute = LojistaInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaEquipeRoute = LojistaEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaConfiguracoesRoute = LojistaConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaClientesRoute = LojistaClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaCampanhasRoute = LojistaCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => LojistaRoute,
} as any)
const LojistaAguardandoRoute = LojistaAguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => LojistaRoute,
} as any)
const FuncionarioVouchersRoute = FuncionarioVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => FuncionarioRoute,
} as any)
const FuncionarioResgatesRoute = FuncionarioResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => FuncionarioRoute,
} as any)
const FuncionarioPontuarRoute = FuncionarioPontuarRouteImport.update({
  id: '/pontuar',
  path: '/pontuar',
  getParentRoute: () => FuncionarioRoute,
} as any)
const FuncionarioPerfilRoute = FuncionarioPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => FuncionarioRoute,
} as any)
const FuncionarioHistoricoRoute = FuncionarioHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => FuncionarioRoute,
} as any)
const FuncionarioClientesRoute = FuncionarioClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => FuncionarioRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWidgetSlugRoute = ApiPublicWidgetSlugRouteImport.update({
  id: '/api/public/widget/$slug',
  path: '/api/public/widget/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookOrigemRoute = ApiPublicWebhookOrigemRouteImport.update({
  id: '/api/public/webhook/$origem',
  path: '/api/public/webhook/$origem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNpsSubmitRoute = ApiPublicNpsSubmitRouteImport.update({
  id: '/api/public/nps/submit',
  path: '/api/public/nps/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificationsDailyRoute =
  ApiPublicHooksNotificationsDailyRouteImport.update({
    id: '/api/public/hooks/notifications-daily',
    path: '/api/public/hooks/notifications-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpirarVouchersRoute =
  ApiPublicHooksExpirarVouchersRouteImport.update({
    id: '/api/public/hooks/expirar-vouchers',
    path: '/api/public/hooks/expirar-vouchers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpirarPontosRoute =
  ApiPublicHooksExpirarPontosRouteImport.update({
    id: '/api/public/hooks/expirar-pontos',
    path: '/api/public/hooks/expirar-pontos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCampanhasAgendadasRoute =
  ApiPublicHooksCampanhasAgendadasRouteImport.update({
    id: '/api/public/hooks/campanhas-agendadas',
    path: '/api/public/hooks/campanhas-agendadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookOlistErpSlugRoute =
  ApiPublicWebhookOlistErpSlugRouteImport.update({
    id: '/api/public/webhook/olist-erp/$slug',
    path: '/api/public/webhook/olist-erp/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/funcionario': typeof FuncionarioRouteWithChildren
  '/lojista': typeof LojistaRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/login': typeof AdminLoginRoute
  '/funcionario/clientes': typeof FuncionarioClientesRoute
  '/funcionario/historico': typeof FuncionarioHistoricoRoute
  '/funcionario/perfil': typeof FuncionarioPerfilRoute
  '/funcionario/pontuar': typeof FuncionarioPontuarRoute
  '/funcionario/resgates': typeof FuncionarioResgatesRoute
  '/funcionario/vouchers': typeof FuncionarioVouchersRoute
  '/lojista/aguardando': typeof LojistaAguardandoRoute
  '/lojista/campanhas': typeof LojistaCampanhasRoute
  '/lojista/clientes': typeof LojistaClientesRoute
  '/lojista/configuracoes': typeof LojistaConfiguracoesRoute
  '/lojista/equipe': typeof LojistaEquipeRoute
  '/lojista/instagram': typeof LojistaInstagramRoute
  '/lojista/lancar-venda': typeof LojistaLancarVendaRoute
  '/lojista/login': typeof LojistaLoginRoute
  '/lojista/notas': typeof LojistaNotasRoute
  '/lojista/nps': typeof LojistaNpsRoute
  '/lojista/onboarding': typeof LojistaOnboardingRoute
  '/lojista/personalizacao': typeof LojistaPersonalizacaoRoute
  '/lojista/produtos': typeof LojistaProdutosRoute
  '/lojista/promocoes': typeof LojistaPromocoesRoute
  '/lojista/resgates': typeof LojistaResgatesRoute
  '/lojista/sorteios': typeof LojistaSorteiosRoute
  '/lojista/vale-presente': typeof LojistaValePresenteRoute
  '/lojista/widget': typeof LojistaWidgetRoute
  '/nota/$slug': typeof NotaSlugRoute
  '/nps/$id': typeof NpsIdRoute
  '/vale/$codigo': typeof ValeCodigoRoute
  '/admin/': typeof AdminIndexRoute
  '/funcionario/': typeof FuncionarioIndexRoute
  '/lojista/': typeof LojistaIndexRoute
  '/api/public/hooks/campanhas-agendadas': typeof ApiPublicHooksCampanhasAgendadasRoute
  '/api/public/hooks/expirar-pontos': typeof ApiPublicHooksExpirarPontosRoute
  '/api/public/hooks/expirar-vouchers': typeof ApiPublicHooksExpirarVouchersRoute
  '/api/public/hooks/notifications-daily': typeof ApiPublicHooksNotificationsDailyRoute
  '/api/public/nps/submit': typeof ApiPublicNpsSubmitRoute
  '/api/public/webhook/$origem': typeof ApiPublicWebhookOrigemRoute
  '/api/public/widget/$slug': typeof ApiPublicWidgetSlugRoute
  '/api/public/webhook/olist-erp/$slug': typeof ApiPublicWebhookOlistErpSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/cadastro': typeof CadastroRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/login': typeof AdminLoginRoute
  '/funcionario/clientes': typeof FuncionarioClientesRoute
  '/funcionario/historico': typeof FuncionarioHistoricoRoute
  '/funcionario/perfil': typeof FuncionarioPerfilRoute
  '/funcionario/pontuar': typeof FuncionarioPontuarRoute
  '/funcionario/resgates': typeof FuncionarioResgatesRoute
  '/funcionario/vouchers': typeof FuncionarioVouchersRoute
  '/lojista/aguardando': typeof LojistaAguardandoRoute
  '/lojista/campanhas': typeof LojistaCampanhasRoute
  '/lojista/clientes': typeof LojistaClientesRoute
  '/lojista/configuracoes': typeof LojistaConfiguracoesRoute
  '/lojista/equipe': typeof LojistaEquipeRoute
  '/lojista/instagram': typeof LojistaInstagramRoute
  '/lojista/lancar-venda': typeof LojistaLancarVendaRoute
  '/lojista/login': typeof LojistaLoginRoute
  '/lojista/notas': typeof LojistaNotasRoute
  '/lojista/nps': typeof LojistaNpsRoute
  '/lojista/onboarding': typeof LojistaOnboardingRoute
  '/lojista/personalizacao': typeof LojistaPersonalizacaoRoute
  '/lojista/produtos': typeof LojistaProdutosRoute
  '/lojista/promocoes': typeof LojistaPromocoesRoute
  '/lojista/resgates': typeof LojistaResgatesRoute
  '/lojista/sorteios': typeof LojistaSorteiosRoute
  '/lojista/vale-presente': typeof LojistaValePresenteRoute
  '/lojista/widget': typeof LojistaWidgetRoute
  '/nota/$slug': typeof NotaSlugRoute
  '/nps/$id': typeof NpsIdRoute
  '/vale/$codigo': typeof ValeCodigoRoute
  '/admin': typeof AdminIndexRoute
  '/funcionario': typeof FuncionarioIndexRoute
  '/lojista': typeof LojistaIndexRoute
  '/api/public/hooks/campanhas-agendadas': typeof ApiPublicHooksCampanhasAgendadasRoute
  '/api/public/hooks/expirar-pontos': typeof ApiPublicHooksExpirarPontosRoute
  '/api/public/hooks/expirar-vouchers': typeof ApiPublicHooksExpirarVouchersRoute
  '/api/public/hooks/notifications-daily': typeof ApiPublicHooksNotificationsDailyRoute
  '/api/public/nps/submit': typeof ApiPublicNpsSubmitRoute
  '/api/public/webhook/$origem': typeof ApiPublicWebhookOrigemRoute
  '/api/public/widget/$slug': typeof ApiPublicWidgetSlugRoute
  '/api/public/webhook/olist-erp/$slug': typeof ApiPublicWebhookOlistErpSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/funcionario': typeof FuncionarioRouteWithChildren
  '/lojista': typeof LojistaRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/login': typeof AdminLoginRoute
  '/funcionario/clientes': typeof FuncionarioClientesRoute
  '/funcionario/historico': typeof FuncionarioHistoricoRoute
  '/funcionario/perfil': typeof FuncionarioPerfilRoute
  '/funcionario/pontuar': typeof FuncionarioPontuarRoute
  '/funcionario/resgates': typeof FuncionarioResgatesRoute
  '/funcionario/vouchers': typeof FuncionarioVouchersRoute
  '/lojista/aguardando': typeof LojistaAguardandoRoute
  '/lojista/campanhas': typeof LojistaCampanhasRoute
  '/lojista/clientes': typeof LojistaClientesRoute
  '/lojista/configuracoes': typeof LojistaConfiguracoesRoute
  '/lojista/equipe': typeof LojistaEquipeRoute
  '/lojista/instagram': typeof LojistaInstagramRoute
  '/lojista/lancar-venda': typeof LojistaLancarVendaRoute
  '/lojista/login': typeof LojistaLoginRoute
  '/lojista/notas': typeof LojistaNotasRoute
  '/lojista/nps': typeof LojistaNpsRoute
  '/lojista/onboarding': typeof LojistaOnboardingRoute
  '/lojista/personalizacao': typeof LojistaPersonalizacaoRoute
  '/lojista/produtos': typeof LojistaProdutosRoute
  '/lojista/promocoes': typeof LojistaPromocoesRoute
  '/lojista/resgates': typeof LojistaResgatesRoute
  '/lojista/sorteios': typeof LojistaSorteiosRoute
  '/lojista/vale-presente': typeof LojistaValePresenteRoute
  '/lojista/widget': typeof LojistaWidgetRoute
  '/nota/$slug': typeof NotaSlugRoute
  '/nps/$id': typeof NpsIdRoute
  '/vale/$codigo': typeof ValeCodigoRoute
  '/admin/': typeof AdminIndexRoute
  '/funcionario/': typeof FuncionarioIndexRoute
  '/lojista/': typeof LojistaIndexRoute
  '/api/public/hooks/campanhas-agendadas': typeof ApiPublicHooksCampanhasAgendadasRoute
  '/api/public/hooks/expirar-pontos': typeof ApiPublicHooksExpirarPontosRoute
  '/api/public/hooks/expirar-vouchers': typeof ApiPublicHooksExpirarVouchersRoute
  '/api/public/hooks/notifications-daily': typeof ApiPublicHooksNotificationsDailyRoute
  '/api/public/nps/submit': typeof ApiPublicNpsSubmitRoute
  '/api/public/webhook/$origem': typeof ApiPublicWebhookOrigemRoute
  '/api/public/widget/$slug': typeof ApiPublicWidgetSlugRoute
  '/api/public/webhook/olist-erp/$slug': typeof ApiPublicWebhookOlistErpSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/cadastro'
    | '/funcionario'
    | '/lojista'
    | '/redefinir-senha'
    | '/admin/login'
    | '/funcionario/clientes'
    | '/funcionario/historico'
    | '/funcionario/perfil'
    | '/funcionario/pontuar'
    | '/funcionario/resgates'
    | '/funcionario/vouchers'
    | '/lojista/aguardando'
    | '/lojista/campanhas'
    | '/lojista/clientes'
    | '/lojista/configuracoes'
    | '/lojista/equipe'
    | '/lojista/instagram'
    | '/lojista/lancar-venda'
    | '/lojista/login'
    | '/lojista/notas'
    | '/lojista/nps'
    | '/lojista/onboarding'
    | '/lojista/personalizacao'
    | '/lojista/produtos'
    | '/lojista/promocoes'
    | '/lojista/resgates'
    | '/lojista/sorteios'
    | '/lojista/vale-presente'
    | '/lojista/widget'
    | '/nota/$slug'
    | '/nps/$id'
    | '/vale/$codigo'
    | '/admin/'
    | '/funcionario/'
    | '/lojista/'
    | '/api/public/hooks/campanhas-agendadas'
    | '/api/public/hooks/expirar-pontos'
    | '/api/public/hooks/expirar-vouchers'
    | '/api/public/hooks/notifications-daily'
    | '/api/public/nps/submit'
    | '/api/public/webhook/$origem'
    | '/api/public/widget/$slug'
    | '/api/public/webhook/olist-erp/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/cadastro'
    | '/redefinir-senha'
    | '/admin/login'
    | '/funcionario/clientes'
    | '/funcionario/historico'
    | '/funcionario/perfil'
    | '/funcionario/pontuar'
    | '/funcionario/resgates'
    | '/funcionario/vouchers'
    | '/lojista/aguardando'
    | '/lojista/campanhas'
    | '/lojista/clientes'
    | '/lojista/configuracoes'
    | '/lojista/equipe'
    | '/lojista/instagram'
    | '/lojista/lancar-venda'
    | '/lojista/login'
    | '/lojista/notas'
    | '/lojista/nps'
    | '/lojista/onboarding'
    | '/lojista/personalizacao'
    | '/lojista/produtos'
    | '/lojista/promocoes'
    | '/lojista/resgates'
    | '/lojista/sorteios'
    | '/lojista/vale-presente'
    | '/lojista/widget'
    | '/nota/$slug'
    | '/nps/$id'
    | '/vale/$codigo'
    | '/admin'
    | '/funcionario'
    | '/lojista'
    | '/api/public/hooks/campanhas-agendadas'
    | '/api/public/hooks/expirar-pontos'
    | '/api/public/hooks/expirar-vouchers'
    | '/api/public/hooks/notifications-daily'
    | '/api/public/nps/submit'
    | '/api/public/webhook/$origem'
    | '/api/public/widget/$slug'
    | '/api/public/webhook/olist-erp/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/cadastro'
    | '/funcionario'
    | '/lojista'
    | '/redefinir-senha'
    | '/admin/login'
    | '/funcionario/clientes'
    | '/funcionario/historico'
    | '/funcionario/perfil'
    | '/funcionario/pontuar'
    | '/funcionario/resgates'
    | '/funcionario/vouchers'
    | '/lojista/aguardando'
    | '/lojista/campanhas'
    | '/lojista/clientes'
    | '/lojista/configuracoes'
    | '/lojista/equipe'
    | '/lojista/instagram'
    | '/lojista/lancar-venda'
    | '/lojista/login'
    | '/lojista/notas'
    | '/lojista/nps'
    | '/lojista/onboarding'
    | '/lojista/personalizacao'
    | '/lojista/produtos'
    | '/lojista/promocoes'
    | '/lojista/resgates'
    | '/lojista/sorteios'
    | '/lojista/vale-presente'
    | '/lojista/widget'
    | '/nota/$slug'
    | '/nps/$id'
    | '/vale/$codigo'
    | '/admin/'
    | '/funcionario/'
    | '/lojista/'
    | '/api/public/hooks/campanhas-agendadas'
    | '/api/public/hooks/expirar-pontos'
    | '/api/public/hooks/expirar-vouchers'
    | '/api/public/hooks/notifications-daily'
    | '/api/public/nps/submit'
    | '/api/public/webhook/$origem'
    | '/api/public/widget/$slug'
    | '/api/public/webhook/olist-erp/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  FuncionarioRoute: typeof FuncionarioRouteWithChildren
  LojistaRoute: typeof LojistaRouteWithChildren
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  NotaSlugRoute: typeof NotaSlugRoute
  NpsIdRoute: typeof NpsIdRoute
  ValeCodigoRoute: typeof ValeCodigoRoute
  ApiPublicHooksCampanhasAgendadasRoute: typeof ApiPublicHooksCampanhasAgendadasRoute
  ApiPublicHooksExpirarPontosRoute: typeof ApiPublicHooksExpirarPontosRoute
  ApiPublicHooksExpirarVouchersRoute: typeof ApiPublicHooksExpirarVouchersRoute
  ApiPublicHooksNotificationsDailyRoute: typeof ApiPublicHooksNotificationsDailyRoute
  ApiPublicNpsSubmitRoute: typeof ApiPublicNpsSubmitRoute
  ApiPublicWebhookOrigemRoute: typeof ApiPublicWebhookOrigemRoute
  ApiPublicWidgetSlugRoute: typeof ApiPublicWidgetSlugRoute
  ApiPublicWebhookOlistErpSlugRoute: typeof ApiPublicWebhookOlistErpSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista': {
      id: '/lojista'
      path: '/lojista'
      fullPath: '/lojista'
      preLoaderRoute: typeof LojistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario': {
      id: '/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof FuncionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista/': {
      id: '/lojista/'
      path: '/'
      fullPath: '/lojista/'
      preLoaderRoute: typeof LojistaIndexRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/funcionario/': {
      id: '/funcionario/'
      path: '/'
      fullPath: '/funcionario/'
      preLoaderRoute: typeof FuncionarioIndexRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vale/$codigo': {
      id: '/vale/$codigo'
      path: '/vale/$codigo'
      fullPath: '/vale/$codigo'
      preLoaderRoute: typeof ValeCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps/$id': {
      id: '/nps/$id'
      path: '/nps/$id'
      fullPath: '/nps/$id'
      preLoaderRoute: typeof NpsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nota/$slug': {
      id: '/nota/$slug'
      path: '/nota/$slug'
      fullPath: '/nota/$slug'
      preLoaderRoute: typeof NotaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista/widget': {
      id: '/lojista/widget'
      path: '/widget'
      fullPath: '/lojista/widget'
      preLoaderRoute: typeof LojistaWidgetRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/vale-presente': {
      id: '/lojista/vale-presente'
      path: '/vale-presente'
      fullPath: '/lojista/vale-presente'
      preLoaderRoute: typeof LojistaValePresenteRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/sorteios': {
      id: '/lojista/sorteios'
      path: '/sorteios'
      fullPath: '/lojista/sorteios'
      preLoaderRoute: typeof LojistaSorteiosRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/resgates': {
      id: '/lojista/resgates'
      path: '/resgates'
      fullPath: '/lojista/resgates'
      preLoaderRoute: typeof LojistaResgatesRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/promocoes': {
      id: '/lojista/promocoes'
      path: '/promocoes'
      fullPath: '/lojista/promocoes'
      preLoaderRoute: typeof LojistaPromocoesRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/produtos': {
      id: '/lojista/produtos'
      path: '/produtos'
      fullPath: '/lojista/produtos'
      preLoaderRoute: typeof LojistaProdutosRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/personalizacao': {
      id: '/lojista/personalizacao'
      path: '/personalizacao'
      fullPath: '/lojista/personalizacao'
      preLoaderRoute: typeof LojistaPersonalizacaoRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/onboarding': {
      id: '/lojista/onboarding'
      path: '/onboarding'
      fullPath: '/lojista/onboarding'
      preLoaderRoute: typeof LojistaOnboardingRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/nps': {
      id: '/lojista/nps'
      path: '/nps'
      fullPath: '/lojista/nps'
      preLoaderRoute: typeof LojistaNpsRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/notas': {
      id: '/lojista/notas'
      path: '/notas'
      fullPath: '/lojista/notas'
      preLoaderRoute: typeof LojistaNotasRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/login': {
      id: '/lojista/login'
      path: '/login'
      fullPath: '/lojista/login'
      preLoaderRoute: typeof LojistaLoginRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/lancar-venda': {
      id: '/lojista/lancar-venda'
      path: '/lancar-venda'
      fullPath: '/lojista/lancar-venda'
      preLoaderRoute: typeof LojistaLancarVendaRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/instagram': {
      id: '/lojista/instagram'
      path: '/instagram'
      fullPath: '/lojista/instagram'
      preLoaderRoute: typeof LojistaInstagramRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/equipe': {
      id: '/lojista/equipe'
      path: '/equipe'
      fullPath: '/lojista/equipe'
      preLoaderRoute: typeof LojistaEquipeRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/configuracoes': {
      id: '/lojista/configuracoes'
      path: '/configuracoes'
      fullPath: '/lojista/configuracoes'
      preLoaderRoute: typeof LojistaConfiguracoesRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/clientes': {
      id: '/lojista/clientes'
      path: '/clientes'
      fullPath: '/lojista/clientes'
      preLoaderRoute: typeof LojistaClientesRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/campanhas': {
      id: '/lojista/campanhas'
      path: '/campanhas'
      fullPath: '/lojista/campanhas'
      preLoaderRoute: typeof LojistaCampanhasRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/lojista/aguardando': {
      id: '/lojista/aguardando'
      path: '/aguardando'
      fullPath: '/lojista/aguardando'
      preLoaderRoute: typeof LojistaAguardandoRouteImport
      parentRoute: typeof LojistaRoute
    }
    '/funcionario/vouchers': {
      id: '/funcionario/vouchers'
      path: '/vouchers'
      fullPath: '/funcionario/vouchers'
      preLoaderRoute: typeof FuncionarioVouchersRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/funcionario/resgates': {
      id: '/funcionario/resgates'
      path: '/resgates'
      fullPath: '/funcionario/resgates'
      preLoaderRoute: typeof FuncionarioResgatesRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/funcionario/pontuar': {
      id: '/funcionario/pontuar'
      path: '/pontuar'
      fullPath: '/funcionario/pontuar'
      preLoaderRoute: typeof FuncionarioPontuarRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/funcionario/perfil': {
      id: '/funcionario/perfil'
      path: '/perfil'
      fullPath: '/funcionario/perfil'
      preLoaderRoute: typeof FuncionarioPerfilRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/funcionario/historico': {
      id: '/funcionario/historico'
      path: '/historico'
      fullPath: '/funcionario/historico'
      preLoaderRoute: typeof FuncionarioHistoricoRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/funcionario/clientes': {
      id: '/funcionario/clientes'
      path: '/clientes'
      fullPath: '/funcionario/clientes'
      preLoaderRoute: typeof FuncionarioClientesRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/widget/$slug': {
      id: '/api/public/widget/$slug'
      path: '/api/public/widget/$slug'
      fullPath: '/api/public/widget/$slug'
      preLoaderRoute: typeof ApiPublicWidgetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/$origem': {
      id: '/api/public/webhook/$origem'
      path: '/api/public/webhook/$origem'
      fullPath: '/api/public/webhook/$origem'
      preLoaderRoute: typeof ApiPublicWebhookOrigemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nps/submit': {
      id: '/api/public/nps/submit'
      path: '/api/public/nps/submit'
      fullPath: '/api/public/nps/submit'
      preLoaderRoute: typeof ApiPublicNpsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notifications-daily': {
      id: '/api/public/hooks/notifications-daily'
      path: '/api/public/hooks/notifications-daily'
      fullPath: '/api/public/hooks/notifications-daily'
      preLoaderRoute: typeof ApiPublicHooksNotificationsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expirar-vouchers': {
      id: '/api/public/hooks/expirar-vouchers'
      path: '/api/public/hooks/expirar-vouchers'
      fullPath: '/api/public/hooks/expirar-vouchers'
      preLoaderRoute: typeof ApiPublicHooksExpirarVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expirar-pontos': {
      id: '/api/public/hooks/expirar-pontos'
      path: '/api/public/hooks/expirar-pontos'
      fullPath: '/api/public/hooks/expirar-pontos'
      preLoaderRoute: typeof ApiPublicHooksExpirarPontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campanhas-agendadas': {
      id: '/api/public/hooks/campanhas-agendadas'
      path: '/api/public/hooks/campanhas-agendadas'
      fullPath: '/api/public/hooks/campanhas-agendadas'
      preLoaderRoute: typeof ApiPublicHooksCampanhasAgendadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/olist-erp/$slug': {
      id: '/api/public/webhook/olist-erp/$slug'
      path: '/api/public/webhook/olist-erp/$slug'
      fullPath: '/api/public/webhook/olist-erp/$slug'
      preLoaderRoute: typeof ApiPublicWebhookOlistErpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FuncionarioRouteChildren {
  FuncionarioClientesRoute: typeof FuncionarioClientesRoute
  FuncionarioHistoricoRoute: typeof FuncionarioHistoricoRoute
  FuncionarioPerfilRoute: typeof FuncionarioPerfilRoute
  FuncionarioPontuarRoute: typeof FuncionarioPontuarRoute
  FuncionarioResgatesRoute: typeof FuncionarioResgatesRoute
  FuncionarioVouchersRoute: typeof FuncionarioVouchersRoute
  FuncionarioIndexRoute: typeof FuncionarioIndexRoute
}

const FuncionarioRouteChildren: FuncionarioRouteChildren = {
  FuncionarioClientesRoute: FuncionarioClientesRoute,
  FuncionarioHistoricoRoute: FuncionarioHistoricoRoute,
  FuncionarioPerfilRoute: FuncionarioPerfilRoute,
  FuncionarioPontuarRoute: FuncionarioPontuarRoute,
  FuncionarioResgatesRoute: FuncionarioResgatesRoute,
  FuncionarioVouchersRoute: FuncionarioVouchersRoute,
  FuncionarioIndexRoute: FuncionarioIndexRoute,
}

const FuncionarioRouteWithChildren = FuncionarioRoute._addFileChildren(
  FuncionarioRouteChildren,
)

interface LojistaRouteChildren {
  LojistaAguardandoRoute: typeof LojistaAguardandoRoute
  LojistaCampanhasRoute: typeof LojistaCampanhasRoute
  LojistaClientesRoute: typeof LojistaClientesRoute
  LojistaConfiguracoesRoute: typeof LojistaConfiguracoesRoute
  LojistaEquipeRoute: typeof LojistaEquipeRoute
  LojistaInstagramRoute: typeof LojistaInstagramRoute
  LojistaLancarVendaRoute: typeof LojistaLancarVendaRoute
  LojistaLoginRoute: typeof LojistaLoginRoute
  LojistaNotasRoute: typeof LojistaNotasRoute
  LojistaNpsRoute: typeof LojistaNpsRoute
  LojistaOnboardingRoute: typeof LojistaOnboardingRoute
  LojistaPersonalizacaoRoute: typeof LojistaPersonalizacaoRoute
  LojistaProdutosRoute: typeof LojistaProdutosRoute
  LojistaPromocoesRoute: typeof LojistaPromocoesRoute
  LojistaResgatesRoute: typeof LojistaResgatesRoute
  LojistaSorteiosRoute: typeof LojistaSorteiosRoute
  LojistaValePresenteRoute: typeof LojistaValePresenteRoute
  LojistaWidgetRoute: typeof LojistaWidgetRoute
  LojistaIndexRoute: typeof LojistaIndexRoute
}

const LojistaRouteChildren: LojistaRouteChildren = {
  LojistaAguardandoRoute: LojistaAguardandoRoute,
  LojistaCampanhasRoute: LojistaCampanhasRoute,
  LojistaClientesRoute: LojistaClientesRoute,
  LojistaConfiguracoesRoute: LojistaConfiguracoesRoute,
  LojistaEquipeRoute: LojistaEquipeRoute,
  LojistaInstagramRoute: LojistaInstagramRoute,
  LojistaLancarVendaRoute: LojistaLancarVendaRoute,
  LojistaLoginRoute: LojistaLoginRoute,
  LojistaNotasRoute: LojistaNotasRoute,
  LojistaNpsRoute: LojistaNpsRoute,
  LojistaOnboardingRoute: LojistaOnboardingRoute,
  LojistaPersonalizacaoRoute: LojistaPersonalizacaoRoute,
  LojistaProdutosRoute: LojistaProdutosRoute,
  LojistaPromocoesRoute: LojistaPromocoesRoute,
  LojistaResgatesRoute: LojistaResgatesRoute,
  LojistaSorteiosRoute: LojistaSorteiosRoute,
  LojistaValePresenteRoute: LojistaValePresenteRoute,
  LojistaWidgetRoute: LojistaWidgetRoute,
  LojistaIndexRoute: LojistaIndexRoute,
}

const LojistaRouteWithChildren =
  LojistaRoute._addFileChildren(LojistaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  FuncionarioRoute: FuncionarioRouteWithChildren,
  LojistaRoute: LojistaRouteWithChildren,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  NotaSlugRoute: NotaSlugRoute,
  NpsIdRoute: NpsIdRoute,
  ValeCodigoRoute: ValeCodigoRoute,
  ApiPublicHooksCampanhasAgendadasRoute: ApiPublicHooksCampanhasAgendadasRoute,
  ApiPublicHooksExpirarPontosRoute: ApiPublicHooksExpirarPontosRoute,
  ApiPublicHooksExpirarVouchersRoute: ApiPublicHooksExpirarVouchersRoute,
  ApiPublicHooksNotificationsDailyRoute: ApiPublicHooksNotificationsDailyRoute,
  ApiPublicNpsSubmitRoute: ApiPublicNpsSubmitRoute,
  ApiPublicWebhookOrigemRoute: ApiPublicWebhookOrigemRoute,
  ApiPublicWidgetSlugRoute: ApiPublicWidgetSlugRoute,
  ApiPublicWebhookOlistErpSlugRoute: ApiPublicWebhookOlistErpSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
