/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedCargosRouteImport } from './routes/_authenticated/cargos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedPremiosRouteImport } from './routes/_authenticated/premios'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedConfiguracoesImportarRouteImport } from './routes/_authenticated/configuracoes.importar'
import { Route as AuthenticatedConfiguracoesOlistRouteImport } from './routes/_authenticated/configuracoes.olist'
import { Route as AuthenticatedVendasIdRouteImport } from './routes/_authenticated/vendas.$id'
import { Route as ApiPublicHooksOlistSyncRouteImport } from './routes/api/public/hooks/olist-sync'
import { Route as ApiPublicHooksOlistWebhookRouteImport } from './routes/api/public/hooks/olist-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCargosRoute = AuthenticatedCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiosRoute = AuthenticatedPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesImportarRoute =
  AuthenticatedConfiguracoesImportarRouteImport.update({
    id: '/configuracoes/importar',
    path: '/configuracoes/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesOlistRoute =
  AuthenticatedConfiguracoesOlistRouteImport.update({
    id: '/configuracoes/olist',
    path: '/configuracoes/olist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasIdRoute = AuthenticatedVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksOlistSyncRoute = ApiPublicHooksOlistSyncRouteImport.update({
  id: '/api/public/hooks/olist-sync',
  path: '/api/public/hooks/olist-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOlistWebhookRoute =
  ApiPublicHooksOlistWebhookRouteImport.update({
    id: '/api/public/hooks/olist-webhook',
    path: '/api/public/hooks/olist-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/premios': typeof AuthenticatedPremiosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/configuracoes/importar': typeof AuthenticatedConfiguracoesImportarRoute
  '/configuracoes/olist': typeof AuthenticatedConfiguracoesOlistRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/api/public/hooks/olist-sync': typeof ApiPublicHooksOlistSyncRoute
  '/api/public/hooks/olist-webhook': typeof ApiPublicHooksOlistWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/premios': typeof AuthenticatedPremiosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/configuracoes/importar': typeof AuthenticatedConfiguracoesImportarRoute
  '/configuracoes/olist': typeof AuthenticatedConfiguracoesOlistRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/api/public/hooks/olist-sync': typeof ApiPublicHooksOlistSyncRoute
  '/api/public/hooks/olist-webhook': typeof ApiPublicHooksOlistWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/cargos': typeof AuthenticatedCargosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/premios': typeof AuthenticatedPremiosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/configuracoes/importar': typeof AuthenticatedConfiguracoesImportarRoute
  '/_authenticated/configuracoes/olist': typeof AuthenticatedConfiguracoesOlistRoute
  '/_authenticated/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/api/public/hooks/olist-sync': typeof ApiPublicHooksOlistSyncRoute
  '/api/public/hooks/olist-webhook': typeof ApiPublicHooksOlistWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/setup'
    | '/sitemap.xml'
    | '/auditoria'
    | '/caixa'
    | '/cargos'
    | '/dashboard'
    | '/funcionarios'
    | '/premios'
    | '/clientes/$id'
    | '/configuracoes/importar'
    | '/configuracoes/olist'
    | '/vendas/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/api/public/hooks/olist-sync'
    | '/api/public/hooks/olist-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/setup'
    | '/sitemap.xml'
    | '/auditoria'
    | '/caixa'
    | '/cargos'
    | '/dashboard'
    | '/funcionarios'
    | '/premios'
    | '/clientes/$id'
    | '/configuracoes/importar'
    | '/configuracoes/olist'
    | '/vendas/$id'
    | '/clientes'
    | '/configuracoes'
    | '/api/public/hooks/olist-sync'
    | '/api/public/hooks/olist-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/setup'
    | '/sitemap.xml'
    | '/_authenticated/auditoria'
    | '/_authenticated/caixa'
    | '/_authenticated/cargos'
    | '/_authenticated/dashboard'
    | '/_authenticated/funcionarios'
    | '/_authenticated/premios'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/configuracoes/importar'
    | '/_authenticated/configuracoes/olist'
    | '/_authenticated/vendas/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/configuracoes/'
    | '/api/public/hooks/olist-sync'
    | '/api/public/hooks/olist-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksOlistSyncRoute: typeof ApiPublicHooksOlistSyncRoute
  ApiPublicHooksOlistWebhookRoute: typeof ApiPublicHooksOlistWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargos': {
      id: '/_authenticated/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AuthenticatedCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premios': {
      id: '/_authenticated/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof AuthenticatedPremiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/importar': {
      id: '/_authenticated/configuracoes/importar'
      path: '/configuracoes/importar'
      fullPath: '/configuracoes/importar'
      preLoaderRoute: typeof AuthenticatedConfiguracoesImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/olist': {
      id: '/_authenticated/configuracoes/olist'
      path: '/configuracoes/olist'
      fullPath: '/configuracoes/olist'
      preLoaderRoute: typeof AuthenticatedConfiguracoesOlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/$id': {
      id: '/_authenticated/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof AuthenticatedVendasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/olist-sync': {
      id: '/api/public/hooks/olist-sync'
      path: '/api/public/hooks/olist-sync'
      fullPath: '/api/public/hooks/olist-sync'
      preLoaderRoute: typeof ApiPublicHooksOlistSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/olist-webhook': {
      id: '/api/public/hooks/olist-webhook'
      path: '/api/public/hooks/olist-webhook'
      fullPath: '/api/public/hooks/olist-webhook'
      preLoaderRoute: typeof ApiPublicHooksOlistWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCargosRoute: typeof AuthenticatedCargosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedPremiosRoute: typeof AuthenticatedPremiosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedConfiguracoesImportarRoute: typeof AuthenticatedConfiguracoesImportarRoute
  AuthenticatedConfiguracoesOlistRoute: typeof AuthenticatedConfiguracoesOlistRoute
  AuthenticatedVendasIdRoute: typeof AuthenticatedVendasIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCargosRoute: AuthenticatedCargosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedPremiosRoute: AuthenticatedPremiosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedConfiguracoesImportarRoute:
    AuthenticatedConfiguracoesImportarRoute,
  AuthenticatedConfiguracoesOlistRoute: AuthenticatedConfiguracoesOlistRoute,
  AuthenticatedVendasIdRoute: AuthenticatedVendasIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksOlistSyncRoute: ApiPublicHooksOlistSyncRoute,
  ApiPublicHooksOlistWebhookRoute: ApiPublicHooksOlistWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
