// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfmloyhmemkfhkwhokph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbWxveWhtZW1rZmhrd2hva3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwNjA0ODIsImV4cCI6MjA5OTYzNjQ4Mn0.iUC_JvPsJwLAO4vbOxVzZTasQySkN-aL4899gig13xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});